### ISSUE TITLE
Definición BBPP

### ISSUE THREAD

**Issue by piaacv** [IsaMonsalves/Memorymatch#12]
- Code Review
- Trabajo por ramas: NO TOCAR EL MAIN 👀💣
- Crear ramas por tareas 💡
- Nombre rama según estructura: Ej: función-nombre tarea
- Commit descriptivos

**Comment by Natalia392** [comment]
[Cómo hacer commits](https://www.freecodecamp.org/espanol/news/como-escribir-un-buen-mensaje-de-commit/)
[Manejo de ramas](https://dev.to/konami12/recomendaciones-para-el-manejo-de-ramas-3hmi)

**Comment by piaacv** [comment]
![Image](https://github.com/IsaMonsalves/Memorymatch/assets/122986202/597e7c33-4117-4dcb-85d1-2e0a7a2eccb0)
